services:

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chirayu
      POSTGRES_PASSWORD: chirayu
      POSTGRES_DB: chirayu
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - custom-bridge

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - custom-bridge

  flowgrid:
    image: chirayupatel19/flowgrid:v1
    container_name: flowgrid_monoapp
    ports:
      - "9000:9000"
    environment:
      USERNAME: chirayu
      PASSWORD: chirayu
      SYSTEM_EMAIL_ID: NoreplyFlowGride@gmail.com
      SYSTEM_EMAIL_PASSWORD: root
    depends_on:
      - postgres
      - mailpit
    networks:
      - custom-bridge
    restart: unless-stopped

networks:
  custom-bridge:
    driver: bridge

volumes:
  postgres-data: